spring:
  data:
    mongodb:
      username: medamine
      password: medamine
      host: mongodb
      port: 27017
      database : customer
      authentication-database: admin
server:
  port: 8090

