spring:
  data:
    mongodb:
      username: medamine
      password: medamine
      host: mongodb
      port: 27017
      database : customer
      authentication-database: admin
eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      default-zone: http://discovery:8761/eureka
server:
  port: 8090

