spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
      routes:
        - id: product-websocket
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - SetRequestHeader=Connection, Upgrade  # Ensure Connection header is set to 'Upgrade'
            - SetRequestHeader=Upgrade, websocket  # Ensure Upgrade header is set to 'websocket'

        - id: product-service
          uri: http://product:8050
          predicates:
            - Path=/api/v1/product/**


       
eureka:

    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
        
server:
  port: 8222
