spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true 
      routes:
        - id: product-service
          uri: ws://product:8050
          predicates:
            - Path=/api/v1/products/**
          filters:
            - SetRequestHeader=Connection, Upgrade  # Ensure Connection header is set to 'Upgrade'
            - SetRequestHeader=Upgrade, websocket  # Ensure Upgrade header is set to 'websocket'
        - id: product-service
          uri: http://product:8050
          predicates:
            - Path=/api/v1/product/**


       
eureka:

    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
      
        
server:
  port: 8222
