spring:
  eureka:
    client:
     service-url:
      defaultZone: http://discovery:8762/eureka/
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
        - id: product-service
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**

server:
  port: 8222
