spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
      routes:
        - id: product-websocket
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE  # Use load-balanced URI with Eureka service ID
          predicates:
            - Path=/api/v1/product/**  # Route path to match
       
eureka:

    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
    instance:
      instanceId: ${spring.application.name}:${random.value}

        
server:
  port: 8222
