spring:
  cloud:
    gateway:
      discovery:
         enable : true
eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
server:
  port: 8222
