spring:
  cloud:
    gateway:
      discovery:
         enable : true
      routes:
        - id: product
          uri: lb://product/
          predicates:
            - Path=/api/v1/product/**

eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
server:
  port: 8222
