
spring:

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
        - id: product-service
          uri: lb://product
          predicates:
            - Path=/api/v1/product/**
eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
server:
  port: 8222
