spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true 
      routes:
        - id: product-websocket
          uri: ws://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - SetRequestHeader=Connection, Upgrade  # Ensure Connection header is set to 'Upgrade'
            - SetRequestHeader=Upgrade, websocket  # Ensure Upgrade header is set to 'websocket'
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE  # Use load-balanced URI with Eureka service ID
          predicates:
            - Path=/api/v1/product/**  # Route path to match
       
eureka:

    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
    instance:
      instanceId: ${spring.application.name}:${random.value}

        
server:
  port: 8222
