spring:
  main:
    web-application-type: reactive
  cloud:
    gateway: 
      routes:
        - id: product-websocket
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - SetRequestHeader=Connection, Upgrade  # Ensure Connection header is set to 'Upgrade'
            - SetRequestHeader=Upgrade, websocket  # Ensure Upgrade header is set to 'websocket'

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
zuul:
  routes:
    product-ws:
      path: /api/v1/products/**
      serviceId: product-service
    product:
      path: /api/v1/product/**
      serviceId: product-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/  # Eureka server URL
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
server:
  port: 8222
