spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:      
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: medamine
    password: medamine
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
eureka:
    instance:
      hostname:
          product
    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

server:
  port: 8050
