spring:
  kafka:
    bootstrapServers: kafka:9092

    producer:
        acks: -1
        bootstrapServers: kafka:9092
        keySerializer: org.apache.kafka.common.serialization.StringSerializer
        valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://ms_pg_sql:5432/postgres
    username: medamine
    password: medamine
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
eureka:
    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
server:
  port: 8050
